Setup sbt-ci-release
scalacenter/scalajs-bundler pull request #401
Opened 2021-03-11 12:51 UTC by cquiroz

This should allow us to release based on `sbt-ci-relese` and directly from github actions.
We'd need to setup the gpg keys and sonatype access credentials though, see

https://github.com/olafurpg/sbt-ci-release

I don't have enough right to put secrets though.
This PR may need several iterations to get it right

2021-03-17 18:47 UTC, cquiroz commented
@sjrd @julienrf I'd need your help to set this up, basically by setting the variables on GitHub

2021-03-17 18:54 UTC, sjrd commented
I'll have a look next week. I'm afraid I'm completely busy this week.

2021-06-04 07:35 UTC, ngbinh commented
@sjrd can we move this forward?

2021-06-04 07:42 UTC, sjrd commented
I am looking at this today, yes.

2021-06-07 13:24 UTC, sjrd requested changes
I have set up the appropriate Repository Secrets now. I have a couple comments to this PR.

2021-06-07 13:24 UTC, sjrd commented on .github/workflows/release.yml
> +          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
You'll have to also add:
```
CI_RELEASE: "; scalajs-bundler-linker/publishSigned; sbt-scalajs-bundler/publishSigned; sbt-web-scalajs-bundler/publishSigned"
CI_SNAPSHOT_RELEASE: "; scalajs-bundler-linker/publish; sbt-scalajs-bundler/publish; sbt-web-scalajs-bundler/publish"
```

2021-06-07 13:24 UTC, sjrd commented on .github/workflows/release.yml
> +          restore-keys: ${{ runner.os }}-sbt-
Is there a reason this is different than what we have in our existing https://github.com/scalacenter/scalajs-bundler/blob/master/.github/workflows/ci.yml ?

2021-06-08 17:37 UTC, cquiroz commented
Updated according to the comments

2021-06-08 18:32 UTC, sjrd commented
Thanks. Could you squash everything in a single commit with a clean commit message?

2021-06-08 18:46 UTC, cquiroz commented
ok, squashed

2021-06-08 18:47 UTC, sjrd approved these changes

2021-06-08 19:44 UTC, merged